[pytest]
testpaths = mcchallonge/tests
python_files = test_*.py
python_classes = Test* UnitTest* IntegrationTest*
python_functions = test_*
addopts = 
    -v
    --tb=short
    --strict-markers
log_cli = true
log_cli_level = INFO
